# Generated by Django 4.2 on 2023-05-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='online', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_Price', models.IntegerField(default=50)),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_payment', to='orders.order')),
            ],
        ),
    ]
