# Generated by Django 4.2 on 2023-04-24 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='username'),
        ),
    ]
