# Generated by Django 4.2 on 2023-05-03 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_password2_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='username'),
        ),
    ]
