# Generated by Django 4.2 on 2023-05-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancellation_deadline',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
