# Generated by Django 4.2 on 2023-05-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '__first__'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_deadline',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
