# Generated by Django 4.2 on 2023-05-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_billing_address'),
        ('orders', '0002_remove_order_billing_address_and_more'),
    ]

    operations = [
    ]
